/* =============================================================================
   ENJAZCO — Language Context
   Supports English (LTR) and Arabic (RTL)
   ============================================================================= */

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "en" | "ar";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  isRTL: false,
});

export const useLanguage = () => useContext(LanguageContext);

/* ---------------------------------------------------------------------------
   Translation dictionary
   --------------------------------------------------------------------------- */
const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.commitments": "Ongoing Projects",
    "nav.clients": "Our Clients",
    "nav.maintenance": "Maintenance",
    "nav.why": "Why ENJAZCO",
    "nav.contact": "Contact",
    "nav.cta": "Get In Touch",

    // Hero slides
    "hero.slide1.l1": "WHERE YOUR",
    "hero.slide1.l2": "VISION",
    "hero.slide1.l3": "BECOMES REALITY",
    "hero.slide1.sub": "Al-Enjaz Trading & Contracting Company — delivering world-class infrastructure across Saudi Arabia since 1978.",
    "hero.slide1.tag": "Roads & Bridges — Est. 1978, Riyadh",

    "hero.slide2.l1": "BUILDING",
    "hero.slide2.l2": "TOMORROW'S",
    "hero.slide2.l3": "INFRASTRUCTURE",
    "hero.slide2.sub": "From highways and bridges to large-diameter pipelines — engineered for the Kingdom's future.",
    "hero.slide2.tag": "Civil Construction",

    "hero.slide3.l1": "47+ YEARS",
    "hero.slide3.l2": "OF PROVEN",
    "hero.slide3.l3": "EXCELLENCE",
    "hero.slide3.sub": "Trusted by government ministries and private clients across all regions of Saudi Arabia.",
    "hero.slide3.tag": "Project Management",

    "hero.slide4.l1": "PRECISION",
    "hero.slide4.l2": "ENGINEERING",
    "hero.slide4.l3": "AT SCALE",
    "hero.slide4.sub": "Integrated MEP, structural, utilities, and fit-out works delivered under one trusted contractor.",
    "hero.slide4.tag": "MEP & Structural",

    "hero.slide5.l1": "VISION 2030",
    "hero.slide5.l2": "ALIGNED",
    "hero.slide5.l3": "CONTRACTOR",
    "hero.slide5.sub": "Strategically positioned to support Saudi Arabia's transformative national development agenda.",
    "hero.slide5.tag": "Structural Works",

    "hero.slide6.l1": "500+",
    "hero.slide6.l2": "PROJECTS",
    "hero.slide6.l3": "DELIVERED",
    "hero.slide6.sub": "A proven track record across roads, utilities, pipelines, and civil construction projects.",
    "hero.slide6.tag": "Large Diameter Pipelines",

    "hero.cta.services": "Explore Services",
    "hero.cta.projects": "View Projects",
    "hero.scroll": "Scroll",

    // Stats
    "stats.years": "Years of Excellence",
    "stats.projects": "Projects Delivered",
    "stats.professionals": "Skilled Professionals",
    "stats.specializations": "Core Specializations",

    // About
    "about.label": "Our Story",
    "about.title1": "BUILT ON",
    "about.title2": "TRUST &",
    "about.title3": "EXCELLENCE",
    "about.p1": "Founded in 1978 in Riyadh, Al-Enjaz Trading & Contracting Company (ENJAZCO) has grown from a regional contractor into one of Saudi Arabia's most trusted infrastructure and construction companies.",
    "about.p2": "Over four decades, we have delivered hundreds of landmark projects across roads, bridges, utilities, pipelines, and building works — always upholding the highest standards of quality, safety, and innovation.",
    "about.p3": "As Saudi Arabia accelerates its Vision 2030 transformation, ENJAZCO stands at the forefront — equipped with the expertise, resources, and commitment to help build the Kingdom's future.",
    "about.val1.title": "Quality First",
    "about.val1.desc": "ISO-certified processes and rigorous QA/QC protocols on every project.",
    "about.val2.title": "Safety Culture",
    "about.val2.desc": "Zero-harm philosophy embedded in every operation and site activity.",
    "about.val3.title": "Innovation",
    "about.val3.desc": "Adopting modern construction technologies and sustainable practices.",
    "about.val4.title": "Integrity",
    "about.val4.desc": "Transparent partnerships built on trust, accountability, and results.",
    "about.badge": "Est. 1978",
    "about.chairman.label": "Chairman's Message",
    "about.chairman.title1": "A MESSAGE FROM",
    "about.chairman.title2": "OUR CHAIRMAN",
    "about.chairman.bismillah": "In the name of Allah, the Most Gracious, the Most Merciful",
    "about.chairman.msg1": "Since 1978, we have continued to serve our clients with professionalism and integrity, with a focus on sustainability for future generations. At Al-Enjaz Trading and Contracting Company, we are proud of our role in developing the land, as God has promised us.",
    "about.chairman.msg2": "We have contributed to major projects, including government infrastructure, which require precision and strong teamwork. With the economic growth of the Kingdom and Vision 2030, we see great opportunities for success, and with effort and work, God is the giver of success.",
    "about.chairman.role": "Owner & Businessman",
    "about.chairman.name": "Al Sheikh / Finjal Bin Sultan Al Otaibi",
    "about.chairman.company": "Al-Enjaz Trading & Contracting Company",

    // Services
    "services.label": "What We Do",
    "services.title1": "OUR",
    "services.title2": "SPECIALIZATIONS",
    "services.s1.title": "Roads, Bridges & Infrastructure",
    "services.s1.desc": "Design and construction of highways, interchanges, overpasses, and road networks to the highest engineering standards.",
    "services.s2.title": "Civil Construction",
    "services.s2.desc": "Comprehensive civil works including earthworks, foundations, reinforced concrete structures, and site preparation.",
    "services.s3.title": "Utilities & Site Development",
    "services.s3.desc": "Complete utility infrastructure: stormwater drainage, sewerage, electrical networks, and full site development.",
    "services.s4.title": "Large Diameter Pipelines",
    "services.s4.desc": "Installation of potable and reclaimed water transmission pipelines using advanced trenchless and open-cut methods.",
    "services.s5.title": "Project Management",
    "services.s5.desc": "End-to-end project management services covering planning, scheduling, cost control, and stakeholder coordination.",
    "services.s6.title": "Maintenance",
    "services.s6.desc": "Preventive and corrective maintenance programs for roads, infrastructure assets, and built facilities.",
    "services.s7.title": "Fit-Out Works",
    "services.s7.desc": "High-quality interior fit-out and finishing works for commercial, government, and residential projects.",
    "services.s8.title": "MEP Works",
    "services.s8.desc": "Mechanical, Electrical, and Plumbing systems design and installation for all building types and scales.",
    "services.s9.title": "Structural Works",
    "services.s9.desc": "Reinforced concrete and steel structural systems for buildings, industrial facilities, and infrastructure.",

    // Projects
    "projects.label": "Our Work",
    "projects.title1": "FEATURED",
    "projects.title2": "PROJECTS",
    "projects.filter.all": "All",
    "projects.filter.roads": "Roads",
    "projects.filter.bridges": "Bridges",
    "projects.filter.pipelines": "Pipelines",
    "projects.filter.mep": "MEP",
    "projects.legend.video": "Video clip",
    "projects.legend.photo": "Photo",
    "projects.legend.expand": "Click expand icon for fullscreen",
    "projects.photos": "photos",
    "projects.videos": "videos",

    "projects.p1.title": "Bridge and Interchange Projects in Al Baha – Central Region",
    "projects.p1.cat": "Maintenance of Roads",
    "projects.p1.loc": "Al Baha – Central Region, Saudi Arabia",
    "projects.p1.desc": "Design and construction of multiple bridge and interchange projects across Al Baha and the Central Region, improving regional connectivity and traffic infrastructure.",
    "projects.p2.title": "Al-Tantabawi in Mecca, Phase Two, 5 km long",
    "projects.p2.cat": "Roads & Infrastructure",
    "projects.p2.loc": "Mecca, Saudi Arabia",
    "projects.p2.desc": "Construction and development of Al-Tantabawi Road in Mecca, Phase Two, covering a total length of 5 km. Works include road widening, intersection improvements, drainage systems, and road markings.",
    "projects.p3.title": "Shuaiba — Al-Laith Roads Maintenance 307",
    "projects.p3.cat": "Maintenance of Roads",
    "projects.p3.loc": "Shuaiba / Al-Laith, Saudi Arabia",
    "projects.p3.desc": "Strategic road maintenance project covering the Shuaiba to Al-Laith corridor with modern pavement management techniques.",
    "projects.p4.title": "Large Diameter Water Pipeline — Eastern Region",
    "projects.p4.cat": "Large Diameter Pipelines",
    "projects.p4.loc": "Eastern Province, Saudi Arabia",
    "projects.p4.desc": "Installation of large diameter potable water transmission pipeline serving major population centers using advanced trenchless technology.",
    "projects.p5.title": "Highway Bridge Infrastructure — Riyadh",
    "projects.p5.cat": "Roads, Bridges & Infrastructure",
    "projects.p5.loc": "Riyadh, Saudi Arabia",
    "projects.p5.desc": "Design and construction of a multi-span highway bridge featuring prestressed concrete girders and modern traffic management systems.",
    "projects.p6.title": "Commercial Complex MEP & Structural Works",
    "projects.p6.cat": "MEP Works / Structural Works",
    "projects.p6.loc": "Riyadh, Saudi Arabia",
    "projects.p6.desc": "Integrated MEP and structural works for a large commercial development, encompassing HVAC, electrical distribution, and reinforced concrete frame.",
    "projects.p7.title": "Rock Cutting Stabilization Works — SAR Network",
    "projects.p7.cat": "Structural Works / Geotechnical Engineering",
    "projects.p7.loc": "Multiple Locations, Saudi Arabia",
    "projects.p7.desc": "Rock cutting stabilization at 6 critical locations along the Saudi Arabia Railways (SAR) network — EWR and NSR lines. Scope includes site assessment, slope stability analysis (LEM & FEM), rock slope stabilization design, and construction of stable slope profiles over 12 months.",
    "projects.filter.structural": "Structural",
    "projects.p8.title": "Earthworks Overview — NEOM Modules 46–47",
    "projects.p8.cat": "Bulk Excavation / Rock Cutting / Controlled Blasting",
    "projects.p8.loc": "NEOM, Tabuk Region, Saudi Arabia",
    "projects.p8.desc": "Mega-scale bulk excavation at NEOM Modules 46–47: 18,000,000 m³ excavated in 8 months with 95,000 m³/day average production. Deep cuts exceeding 50m through soil and weathered rock using mechanical ripping, hydraulic breaking, and controlled blasting — with full HSE compliance.",
    "projects.filter.earthworks": "Earthworks",
    "projects.p9.title": "Bridge Projects in Al Hassa, Spanning 1.6 km",
    "projects.p9.cat": "Roads, Bridges & Infrastructure",
    "projects.p9.loc": "Al Hassa, Eastern Province, Saudi Arabia",
    "projects.p9.desc": "Construction of multiple bridge structures across Al Hassa spanning a total of 1.6 km. The project encompasses reinforced concrete bridge decks, substructure works, and full road integration in the Eastern Province.",
    "projects.p10.title": "Al Wajh Interchange Project",
    "projects.p10.cat": "Roads, Bridges & Infrastructure",
    "projects.p10.loc": "Al Wajh, Tabuk Region, Saudi Arabia",
    "projects.p10.desc": "Design and construction of a major interchange in Al Wajh featuring multi-level roundabouts, elevated ramps, and full road network integration across the desert terrain of the Tabuk region.",
    "projects.p11.title": "Bridge and Interchange in Hufof",
    "projects.p11.cat": "Roads, Bridges & Infrastructure",
    "projects.p11.loc": "Hufof (Al Ahsa), Eastern Province, Saudi Arabia",
    "projects.p11.desc": "Construction of bridge structures and interchange facilities in Hufof, Al Ahsa, including underpasses, elevated road sections, and railway crossing bridges as part of the regional transport infrastructure upgrade.",
    "projects.p12.title": "Construction of Jeddah–Makkah Expressway",
    "projects.p12.cat": "Roads, Bridges & Infrastructure",
    "projects.p12.loc": "Jeddah–Makkah Corridor, Makkah Region, Saudi Arabia",
    "projects.p12.desc": "Construction of the Jeddah–Makkah Expressway, a high-capacity multi-lane highway connecting the two holy cities. Works include earthworks, pavement, bridges, interchanges, and full road furniture across a challenging mountainous and desert terrain.",
    "projects.p13.title": "Construction of Roads and Bridges in Al Baha Region",
    "projects.p13.cat": "Roads, Bridges & Infrastructure",
    "projects.p13.loc": "Al Baha Region, Saudi Arabia",
    "projects.p13.desc": "Comprehensive road and bridge construction across the Al Baha region, covering mountainous terrain and valley crossings. Works include multi-lane road construction, bridge structures, retaining walls, and drainage systems.",
    "projects.p14.title": "Al-Sail Road with the Fourth Ring Road and Bridge",
    "projects.p14.cat": "Roads, Bridges & Infrastructure",
    "projects.p14.loc": "Makkah Region, Saudi Arabia",
    "projects.p14.desc": "Construction of Al-Sail Road interchange with the Fourth Ring Road, featuring multi-level intersections, elevated bridges, and high-capacity expressways connecting key districts around Makkah Al-Mukarramah.",
    "projects.p15.title": "Al-Sail Road — 2 Bridges",
    "projects.p15.cat": "Bridges & Infrastructure",
    "projects.p15.loc": "Makkah Region, Saudi Arabia",
    "projects.p15.desc": "Construction of two major bridges on Al-Sail Road in Makkah, providing critical grade-separated crossings to improve traffic flow and reduce congestion at key intersections.",
    "projects.p16.title": "Jubail–Buraydah Independent Water Transmission Pipeline (IWTP) Project",
    "projects.p16.cat": "Large Diameter Pipelines",
    "projects.p16.loc": "Eastern Province to Qassim Region, Saudi Arabia",
    "projects.p16.desc": "Construction of the Jubail–Buraydah Independent Water Transmission Pipeline (IWTP), a major large-diameter pipeline project transporting desalinated water from Jubail Industrial City to Buraydah in the Qassim Region, spanning hundreds of kilometres across the Saudi desert.",

    // Why
    "why.label": "Why Choose Us",
    "why.title1": "THE ENJAZCO",
    "why.title2": "ADVANTAGE",
    "why.sub": "Four decades of engineering excellence, backed by a skilled workforce and a commitment to Vision 2030.",
    "why.w1.title": "Government-Grade Quality",
    "why.w1.desc": "Approved contractor for Saudi ministries and government agencies with a flawless compliance record.",
    "why.w2.title": "Integrated Capabilities",
    "why.w2.desc": "Nine specializations under one roof — eliminating coordination risk and reducing project timelines.",
    "why.w3.title": "Experienced Workforce",
    "why.w3.desc": "1,001+ skilled engineers, technicians, and site professionals with deep domain expertise.",
    "why.w4.title": "Vision 2030 Ready",
    "why.w4.desc": "Strategically aligned with Saudi Arabia's national transformation program and NEOM-era infrastructure demands.",
    "why.w5.title": "HSE Excellence",
    "why.w5.desc": "Industry-leading health, safety, and environmental standards across all project sites.",
    "why.w6.title": "On-Time Delivery",
    "why.w6.desc": "Proven track record of delivering complex projects on schedule and within budget.",
    "why.cta": "Start Your Project",

    // Commitments
    "commit.label": "Our Commitments",
    "commit.title1": "BUILT WITH",
    "commit.title2": "PURPOSE",
    "commit.c1.title": "Health, Safety & Environment",
    "commit.c1.desc": "Zero-harm culture with rigorous HSE management systems, regular audits, and continuous training for all site personnel.",
    "commit.c2.title": "Sustainability",
    "commit.c2.desc": "Minimizing environmental impact through responsible material sourcing, waste reduction, and energy-efficient construction methods.",
    "commit.c3.title": "Community",
    "commit.c3.desc": "Prioritizing local employment, skills development, and community engagement in every region we operate.",
    "commit.c4.title": "Quality Assurance",
    "commit.c4.desc": "ISO-certified quality management systems ensuring every deliverable meets or exceeds client and regulatory specifications.",
    "commit.banner.title": "Ready to Build Something Great?",
    "commit.banner.sub": "Partner with ENJAZCO for your next infrastructure or construction project.",
    "commit.banner.cta": "Request a Proposal",

    // Certifications
    "cert.iso9001.title": "Quality Management",
    "cert.iso9001.desc": "Ensures consistent quality in project delivery, processes, and client satisfaction across all operations.",
    "cert.iso14001.title": "Environmental Management",
    "cert.iso14001.desc": "Demonstrates commitment to minimizing environmental impact and sustainable construction practices.",
    "cert.iso45001.title": "Occupational Health & Safety",
    "cert.iso45001.desc": "Provides a safe and healthy workplace by preventing work-related injury and ill health on all sites.",
    "cert.iso27001.title": "Information Security",
    "cert.iso27001.desc": "Protects company and client data through rigorous information security management systems.",
    "cert.ccc.title": "Cybersecurity Compliance",
    "cert.ccc.desc": "Certified under Saudi Arabia's Cybersecurity Compliance Certification (CCC) framework by NCA.",

    // Contact
    "contact.label": "Get In Touch",
    "contact.title1": "LET'S BUILD",
    "contact.title2": "TOGETHER",
    "contact.sub": "Ready to discuss your next project? Our team is here to help.",
    "contact.form.name": "Full Name",
    "contact.form.email": "Email Address",
    "contact.form.phone": "Phone Number",
    "contact.form.company": "Company / Organization",
    "contact.form.service": "Service of Interest",
    "contact.form.message": "Project Details",
    "contact.form.submit": "Send Message",
    "contact.form.placeholder.name": "Your full name",
    "contact.form.placeholder.email": "your@email.com",
    "contact.form.placeholder.phone": "+966 5X XXX XXXX",
    "contact.form.placeholder.company": "Your company name",
    "contact.form.placeholder.message": "Tell us about your project...",
    "contact.info.address": "Riyadh, Saudi Arabia",
    "contact.info.phoneVal": "+966 11 4655557",

    // Footer
    "footer.tagline": "Building Saudi Arabia's infrastructure since 1978.",
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.about": "About Us",
    "footer.projects": "Projects",
    "footer.careers": "Careers",
    "footer.news": "News",
    "footer.rights": "All rights reserved.",
    "footer.cr": "CR No.",
    "footer.quicklinks": "Quick Links",
    "footer.copy": "© 2026 Al-Enjaz Trading & Contracting Company. All Rights Reserved.",
    "footer.location": "Riyadh, Kingdom of Saudi Arabia",
    "contact.intro": "Ready to discuss your next project? Our team of engineers and project managers is here to help you plan, design, and deliver.",
    "contact.info.hq": "Headquarters",
    "contact.info.phone": "Phone",
    "contact.info.email": "Email",
    "contact.info.jobs": "Jobs & Careers",
    "contact.info.hours": "Working Hours",
    "contact.info.hoursVal": "Sunday – Thursday: 7:00 AM – 3:00 PM",
    "contact.cr.label": "Commercial Registration",
    "contact.cr.value": "Registered in the Kingdom of Saudi Arabia",
    "contact.form.namePh": "Your full name",
    "contact.form.emailPh": "your@email.com",
    "contact.form.companyPh": "Your company name",
    "contact.form.servicePh": "Select a service...",
    "contact.form.messagePh": "Tell us about your project requirements...",
    "contact.success.title": "Message Sent!",
    "contact.success.sub": "Thank you for reaching out. Our team will be in touch within 1–2 business days.",

    // Awards Section
    "awards.eyebrow": "Excellence & Recognition",
    "awards.title": "Awards & Certifications",
    "awards.subtitle": "ENJAZCO's commitment to quality, safety, and innovation is recognised through internationally accredited certifications, regional industry awards, and landmark safety milestones.",
    "awards.cert.heading": "International ISO Certifications",
    "awards.cert.quality": "Quality Management",
    "awards.cert.quality.desc": "Certified for consistent delivery of quality construction services meeting international standards.",
    "awards.cert.env": "Environmental Management",
    "awards.cert.env.desc": "Committed to minimising environmental impact across all project sites and operations.",
    "awards.cert.ohs": "Occupational Health & Safety",
    "awards.cert.ohs.desc": "Ensuring the highest standards of worker safety and occupational health on every project.",
    "awards.cert.edu": "Educational Organisations Management",
    "awards.cert.edu.desc": "Certified management system for training and professional development programmes.",
    "awards.mile.heading": "Safety & Achievement Milestones",
    "awards.mile1.value": "2M+",
    "awards.mile1.label": "Safe Man-Hours",
    "awards.mile1.sub": "NEOM – The Line Project, Zero LTI",
    "awards.mile2.value": "47+",
    "awards.mile2.label": "Years of Excellence",
    "awards.mile2.sub": "Founded 1978 — Serving Saudi Arabia's infrastructure",
    "awards.mile3.value": "250+",
    "awards.mile3.label": "Projects Delivered",
    "awards.mile3.sub": "Across roads, bridges, tunnels, pipelines & buildings",
    "awards.reg.heading": "Regional Awards & Nominations",
    "awards.reg1.year": "2025",
    "awards.reg1.title": "Project Awards Middle East — Infrastructure Excellence",
    "awards.reg1.body": "Recognised for outstanding delivery of large-scale infrastructure projects across the Kingdom, including the Jubail–Buraydah IWTP pipeline.",
    "awards.reg1.org": "Project Awards ME",
    "awards.reg2.year": "2025",
    "awards.reg2.title": "Health & Safety Initiative of the Year",
    "awards.reg2.body": "Nominated for a digital-first safety culture empowering 2,000+ workers on one of Saudi Arabia's most complex infrastructure projects.",
    "awards.reg2.org": "Construction Week KSA Awards",
    "awards.reg3.year": "2024",
    "awards.reg3.title": "NEOM Safety Achievement Award",
    "awards.reg3.body": "Awarded by NEOM for achieving 2 Million Safe Man-Hours with Zero Lost Time Incidents during The Line foundation works.",
    "awards.reg3.org": "NEOM",
    "awards.reg4.year": "2024",
    "awards.reg4.title": "Diamond Sponsor — Highways Saudi Arabia",
    "awards.reg4.body": "Recognised as Diamond Sponsor at Highways Saudi Arabia 2024, reflecting ENJAZCO's leadership in road and bridge construction.",
    "awards.reg4.org": "Highways KSA",
    "awards.gallery.heading": "Award Ceremony Photo Gallery",
  },

  ar: {
    // Navbar
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.services": "خدماتنا",
    "nav.projects": "مشاريعنا",
    "nav.commitments": "المشاريع الجارية",
    "nav.clients": "عملاؤنا",
    "nav.maintenance": "الصيانة",
    "nav.why": "لماذا إنجازكو",
    "nav.contact": "تواصل معنا",
    "nav.cta": "تواصل الآن",

    // Hero slides
    "hero.slide1.l1": "حيث تتحوّل",
    "hero.slide1.l2": "رؤيتك",
    "hero.slide1.l3": "إلى واقع",
    "hero.slide1.sub": "شركة الإنجاز للتجارة والمقاولات — نقدّم بنية تحتية عالمية المستوى في المملكة العربية السعودية منذ عام 1978.",
    "hero.slide1.tag": "الطرق والجسور — تأسست 1978، الرياض",

    "hero.slide2.l1": "نبني",
    "hero.slide2.l2": "بنية تحتية",
    "hero.slide2.l3": "المستقبل",
    "hero.slide2.sub": "من الطرق السريعة والجسور إلى خطوط الأنابيب ذات القطر الكبير — مهندسة لمستقبل المملكة.",
    "hero.slide2.tag": "الإنشاءات المدنية",

    "hero.slide3.l1": "أكثر من",
    "hero.slide3.l2": "47 عاماً",
    "hero.slide3.l3": "من التميّز",
    "hero.slide3.sub": "موثوق من قِبل الوزارات الحكومية والعملاء الخاصين في جميع مناطق المملكة العربية السعودية.",
    "hero.slide3.tag": "إدارة المشاريع",

    "hero.slide4.l1": "هندسة",
    "hero.slide4.l2": "دقيقة",
    "hero.slide4.l3": "على نطاق واسع",
    "hero.slide4.sub": "أعمال الميكانيكا والكهرباء والسباكة والإنشاءات والمرافق والتشطيبات تحت سقف مقاول واحد موثوق.",
    "hero.slide4.tag": "أعمال الميكانيكا والكهرباء والإنشاءات",

    "hero.slide5.l1": "مقاول",
    "hero.slide5.l2": "متوافق مع",
    "hero.slide5.l3": "رؤية 2030",
    "hero.slide5.sub": "موقع استراتيجي لدعم أجندة التنمية الوطنية التحويلية للمملكة العربية السعودية.",
    "hero.slide5.tag": "الأعمال الإنشائية",

    "hero.slide6.l1": "أكثر من",
    "hero.slide6.l2": "500",
    "hero.slide6.l3": "مشروع منجز",
    "hero.slide6.sub": "سجل حافل بالإنجازات في مجالات الطرق والمرافق وخطوط الأنابيب والإنشاءات المدنية.",
    "hero.slide6.tag": "خطوط الأنابيب ذات القطر الكبير",

    "hero.cta.services": "استكشف خدماتنا",
    "hero.cta.projects": "مشاهدة المشاريع",
    "hero.scroll": "تمرير",

    // Stats
    "stats.years": "عاماً من التميّز",
    "stats.projects": "مشروع منجز",
    "stats.professionals": "متخصص ماهر",
    "stats.specializations": "تخصصات رئيسية",

    // About
    "about.label": "قصتنا",
    "about.title1": "مبنيّون على",
    "about.title2": "الثقة",
    "about.title3": "والتميّز",
    "about.p1": "تأسست شركة الإنجاز للتجارة والمقاولات (إنجازكو) عام 1978 في الرياض، ونمت من مقاول إقليمي إلى واحدة من أكثر شركات البنية التحتية والإنشاءات موثوقية في المملكة العربية السعودية.",
    "about.p2": "على مدى أربعة عقود، أنجزنا مئات المشاريع البارزة في مجالات الطرق والجسور والمرافق وخطوط الأنابيب وأعمال البناء — مع الالتزام الدائم بأعلى معايير الجودة والسلامة والابتكار.",
    "about.p3": "مع تسارع تحوّل المملكة العربية السعودية نحو رؤية 2030، تقف إنجازكو في طليعة المشهد — مزودة بالخبرة والموارد والالتزام اللازمة للمساهمة في بناء مستقبل المملكة.",
    "about.val1.title": "الجودة أولاً",
    "about.val1.desc": "عمليات معتمدة بشهادة ISO وبروتوكولات صارمة لضمان الجودة في كل مشروع.",
    "about.val2.title": "ثقافة السلامة",
    "about.val2.desc": "فلسفة الصفر في الحوادث مُدمجة في كل عملية ونشاط ميداني.",
    "about.val3.title": "الابتكار",
    "about.val3.desc": "تبنّي تقنيات البناء الحديثة والممارسات المستدامة.",
    "about.val4.title": "النزاهة",
    "about.val4.desc": "شراكات شفافة مبنية على الثقة والمساءلة والنتائج.",
    "about.badge": "تأسست 1978",
    "about.chairman.label": "كلمة رئيس مجلس الإدارة",
    "about.chairman.title1": "رسالة من",
    "about.chairman.title2": "رئيسنا",
    "about.chairman.bismillah": "بسم الله الرحمن الرحيم، والصلاة والسلام على رسول الله",
    "about.chairman.msg1": "منذ عام 1978، واصلنا خدمة عملائنا باحترافية ونزاهة، مع التركيز على الاستدامة للأجيال القادمة. في شركة الإنجاز للتجارة والمقاولات، نفخر بدورنا في تطوير الأرض، كما وعدنا الله بذلك.",
    "about.chairman.msg2": "لقد أسهمنا في مشاريع كبرى تشمل البنية التحتية الحكومية التي تتطلب الدقة والعمل الجماعي المتماسك. مع النمو الاقتصادي للمملكة ورؤية 2030، نرى فرصاً عظيمة للنجاح، وبالجهد والعمل والله ولي التوفيق.",
    "about.chairman.role": "صاحب الشركة ورجل الأعمال",
    "about.chairman.name": "الشيخ / فنجل بن سلطان العتيبي",
    "about.chairman.company": "شركة الإنجاز للتجارة والمقاولات",

    // Services
    "services.label": "ما نقدّمه",
    "services.title1": "تخصصاتنا",
    "services.title2": "الرئيسية",
    "services.s1.title": "الطرق والجسور والبنية التحتية",
    "services.s1.desc": "تصميم وإنشاء الطرق السريعة والتقاطعات والجسور العلوية وشبكات الطرق وفق أعلى المعايير الهندسية.",
    "services.s2.title": "الإنشاءات المدنية",
    "services.s2.desc": "أعمال مدنية شاملة تشمل أعمال الحفر والأساسات والهياكل الخرسانية المسلحة وتهيئة المواقع.",
    "services.s3.title": "المرافق وتطوير المواقع",
    "services.s3.desc": "بنية تحتية متكاملة للمرافق: صرف مياه الأمطار والصرف الصحي والشبكات الكهربائية والتطوير الكامل للمواقع.",
    "services.s4.title": "خطوط الأنابيب ذات القطر الكبير",
    "services.s4.desc": "تركيب خطوط نقل مياه الشرب والمياه المعالجة باستخدام أساليب متقدمة بدون حفر وبالحفر المفتوح.",
    "services.s5.title": "إدارة المشاريع",
    "services.s5.desc": "خدمات إدارة المشاريع من البداية إلى النهاية تشمل التخطيط والجدولة ومراقبة التكاليف وتنسيق أصحاب المصلحة.",
    "services.s6.title": "الصيانة",
    "services.s6.desc": "برامج الصيانة الوقائية والتصحيحية للطرق والأصول التحتية والمنشآت المبنية.",
    "services.s7.title": "أعمال التشطيبات",
    "services.s7.desc": "أعمال تشطيب داخلي عالية الجودة للمشاريع التجارية والحكومية والسكنية.",
    "services.s8.title": "أعمال الميكانيكا والكهرباء والسباكة",
    "services.s8.desc": "تصميم وتركيب أنظمة الميكانيكا والكهرباء والسباكة لجميع أنواع وأحجام المباني.",
    "services.s9.title": "الأعمال الإنشائية",
    "services.s9.desc": "أنظمة هيكلية من الخرسانة المسلحة والصلب للمباني والمنشآت الصناعية والبنية التحتية.",

    // Projects
    "projects.label": "أعمالنا",
    "projects.title1": "مشاريع",
    "projects.title2": "مميزة",
    "projects.filter.all": "الكل",
    "projects.filter.roads": "طرق",
    "projects.filter.bridges": "جسور",
    "projects.filter.pipelines": "أنابيب",
    "projects.filter.mep": "ميكانيكا وكهرباء",
    "projects.legend.video": "مقطع فيديو",
    "projects.legend.photo": "صورة",
    "projects.legend.expand": "انقر على أيقونة التوسيع للعرض الكامل",
    "projects.photos": "صور",
    "projects.videos": "مقاطع",

    "projects.p1.title": "مشاريع جسور وتقاطعات في الباحة – المنطقة الوسطى",
    "projects.p1.cat": "صيانة الطرق",
    "projects.p1.loc": "الباحة – المنطقة الوسطى، المملكة العربية السعودية",
    "projects.p1.desc": "تصميم وتنفيذ مشاريع جسور وتقاطعات متعددة في الباحة والمنطقة الوسطى، لتحسين الربط الإقليمي وبنية حركة المرور.",
    "projects.p2.title": "طريق التنتباوي بمكة المكرمة، المرحلة الثانية، 5 كم",
    "projects.p2.cat": "الطرق والبنية التحتية",
    "projects.p2.loc": "مكة المكرمة، المملكة العربية السعودية",
    "projects.p2.desc": "عقد صيانة قائم على الأداء لممر الطريق من الزلفي إلى الغاط لضمان أداء الرصف على المدى البعيد والسلامة.",
    "projects.p3.title": "صيانة طرق شعيبة — الليث 307",
    "projects.p3.cat": "صيانة الطرق",
    "projects.p3.loc": "شعيبة / الليث، المملكة العربية السعودية",
    "projects.p3.desc": "مشروع صيانة طرق استراتيجي يغطي ممر شعيبة إلى الليث بأساليب إدارة رصف حديثة.",
    "projects.p4.title": "خط أنابيب مياه ذو قطر كبير — المنطقة الشرقية",
    "projects.p4.cat": "خطوط الأنابيب ذات القطر الكبير",
    "projects.p4.loc": "المنطقة الشرقية، المملكة العربية السعودية",
    "projects.p4.desc": "تركيب خط نقل مياه شرب ذو قطر كبير يخدم مراكز سكانية رئيسية باستخدام تقنية الحفر بدون خندق المتقدمة.",
    "projects.p5.title": "بنية تحتية لجسر طريق سريع — الرياض",
    "projects.p5.cat": "الطرق والجسور والبنية التحتية",
    "projects.p5.loc": "الرياض، المملكة العربية السعودية",
    "projects.p5.desc": "تصميم وإنشاء جسر طريق سريع متعدد البحور يتميز بكمرات خرسانية مسبقة الإجهاد وأنظمة إدارة مرور حديثة.",
    "projects.p6.title": "أعمال الميكانيكا والكهرباء والإنشاءات لمجمع تجاري",
    "projects.p6.cat": "أعمال الميكانيكا والكهرباء / الأعمال الإنشائية",
    "projects.p6.loc": "الرياض، المملكة العربية السعودية",
    "projects.p6.desc": "أعمال متكاملة للميكانيكا والكهرباء والسباكة والإنشاءات لمشروع تجاري كبير يشمل التكييف والتوزيع الكهربائي والهيكل الخرساني.",
    "projects.p7.title": "أعمال تثبيت قطع الصخور — شبكة سار",
    "projects.p7.cat": "أعمال إنشائية / هندسة جيوتقنية",
    "projects.p7.loc": "مواقع متعددة، المملكة العربية السعودية",
    "projects.p7.desc": "تثبيت قطع الصخور في 6 مواقع حرجة على شبكة سكك الحديد السعودية (سار) — خطوط EWR و NSR. يشمل النطاق تقييم الموقع وتحليل استقرار المنحدرات وتصميم تثبيت السفوح الصخرية وتنفيذ أعمال البناء خلال 12 شهراً.",
    "projects.filter.structural": "إنشائي",
    "projects.p8.title": "أعمال الحفر والتسوية — نيوم وحدات 46–47",
    "projects.p8.cat": "حفر بالجملة / قطع الصخور / التفجير المتحكم",
    "projects.p8.loc": "نيوم، منطقة تبوك، المملكة العربية السعودية",
    "projects.p8.desc": "أعمال حفر ضخمة في وحدات نيوم 46-47: 18,000,000 م³ تم حفرها في 8 أشهر بمعدل إنتاج يومي 95,000 م³. قطع عميقة تتجاوز 50 متراً عبر التربة والصخور المتجوية باستخدام التقطيع الميكانيكي والكسر الهيدروليكي والتفجير المتحكم — مع الالتزام الكامل بمعايير الصحة والسلامة والبيئة.",
    "projects.filter.earthworks": "أعمال ترابية",
    "projects.p9.title": "مشاريع جسور في الأحساء بطول 1.6 كم",
    "projects.p9.cat": "الطرق والجسور والبنية التحتية",
    "projects.p9.loc": "الأحساء، المنطقة الشرقية، المملكة العربية السعودية",
    "projects.p9.desc": "إنشاء منشآت جسور متعددة في الأحساء بإجمالي طول 1.6 كيلومتر، تشمل أعمال الأسطح الخرسانية المسلحة والأعمال التحتية والتكامل الكامل مع شبكة الطرق في المنطقة الشرقية.",
    "projects.p10.title": "مشروع تقاطع الوجه",
    "projects.p10.cat": "الطرق والجسور والبنية التحتية",
    "projects.p10.loc": "الوجه، منطقة تبوك، المملكة العربية السعودية",
    "projects.p10.desc": "تصميم وإنشاء تقاطع رئيسي في الوجه يتضمن دوارات متعددة المستويات ومنحدرات مرتفعة وتكاملاً كاملاً مع شبكة الطرق في تضاريس منطقة تبوك الصحراوية.",
    "projects.p11.title": "جسر وتقاطع في الهفوف",
    "projects.p11.cat": "الطرق والجسور والبنية التحتية",
    "projects.p11.loc": "الهفوف (الأحساء)، المنطقة الشرقية، المملكة العربية السعودية",
    "projects.p11.desc": "إنشاء منشآت جسور وتقاطعات في الهفوف بالأحساء، تشمل نفقاً سفلياً وأقساماً مرتفعة وجسور عبور للسكك الحديدية ضمن مشروع تطوير البنية التحتية للنقل الإقليمي.",
    "projects.p12.title": "إنشاء طريق جدة–مكة السريع",
    "projects.p12.cat": "الطرق والجسور والبنية التحتية",
    "projects.p12.loc": "محور جدة–مكة المكرمة، منطقة مكة المكرمة، المملكة العربية السعودية",
    "projects.p12.desc": "إنشاء طريق جدة–مكة السريع، وهو طريق سريع متعدد الحارات يربط المدينتين المقدستين. تشمل الأعمال الحفر والردم والرصف والجسور والتقاطعات وكامل المعدات الطرقية عبر تضاريس جبلية وصحراوية.",
    "projects.p13.title": "إنشاء طرق وجسور في منطقة الباحة",
    "projects.p13.cat": "الطرق والجسور والبنية التحتية",
    "projects.p13.loc": "منطقة الباحة، المملكة العربية السعودية",
    "projects.p13.desc": "إنشاء شامل للطرق والجسور في منطقة الباحة يغطي التضاريس الجبلية وعبور الأودية. تشمل الأعمال إنشاء طرق متعددة الحارات ومنشآت الجسور وجدران الاستناد وأنظمة الصرف.",
    "projects.p14.title": "طريق السيل مع الطريق الدائري الرابع والجسر",
    "projects.p14.cat": "الطرق والجسور والبنية التحتية",
    "projects.p14.loc": "منطقة مكة المكرمة، المملكة العربية السعودية",
    "projects.p14.desc": "مشروع طريق السيل مع الطريق الدائري الرابع، يشمل إنشاء تقاطعات متعددة المستويات وجسور متطورة وطرق سريعة تربط المناطق الحيوية في محيط مكة المكرمة.",
    "projects.p15.title": "طريق السيل — جسران",
    "projects.p15.cat": "الجسور والبنية التحتية",
    "projects.p15.loc": "منطقة مكة المكرمة، المملكة العربية السعودية",
    "projects.p15.desc": "إنشاء جسرين رئيسيين على طريق السيل في مكة المكرمة، يوفران تقاطعات منفصلة المستويات لتحسين تدفق حركة المرور وتقليل الازدحام عند التقاطعات الرئيسية.",
    "projects.p16.title": "مشروع خط نقل المياه المستقل من الجبيل إلى بريدة (IWTP)",
    "projects.p16.cat": "خطوط الأنابيب ذات القطر الكبير",
    "projects.p16.loc": "المنطقة الشرقية إلى منطقة القصيم، المملكة العربية السعودية",
    "projects.p16.desc": "إنشاء خط نقل المياه المستقل من الجبيل إلى بريدة (IWTP)، وهو مشروع ضخم لخط أنابيب ذي قطر كبير لنقل المياه المحلاة من مدينة الجبيل الصناعية إلى بريدة في منطقة القصيم، يمتد لمئات الكيلومترات عبر الصحراء السعودية.",

    // Why
    "why.label": "لماذا تختارنا",
    "why.title1": "ميزة",
    "why.title2": "إنجازكو",
    "why.sub": "أربعة عقود من التميز الهندسي، مدعومة بكوادر بشرية ماهرة والتزام راسخ برؤية 2030.",
    "why.w1.title": "جودة على مستوى حكومي",
    "why.w1.desc": "مقاول معتمد لدى الوزارات والجهات الحكومية السعودية بسجل امتثال لا تشوبه شائبة.",
    "why.w2.title": "قدرات متكاملة",
    "why.w2.desc": "تسعة تخصصات تحت سقف واحد — تُقلل مخاطر التنسيق وتُقصّر الجداول الزمنية للمشاريع.",
    "why.w3.title": "كوادر بشرية متمرسة",
    "why.w3.desc": "أكثر من 1001 مهندس وفني ومتخصص ميداني يمتلكون خبرة عميقة في مجالاتهم.",
    "why.w4.title": "جاهزون لرؤية 2030",
    "why.w4.desc": "متوافقون استراتيجياً مع برنامج التحوّل الوطني السعودي ومتطلبات البنية التحتية لعصر نيوم.",
    "why.w5.title": "تميّز في الصحة والسلامة والبيئة",
    "why.w5.desc": "معايير رائدة في الصحة والسلامة والبيئة في جميع مواقع المشاريع.",
    "why.w6.title": "التسليم في الوقت المحدد",
    "why.w6.desc": "سجل حافل بتسليم المشاريع المعقدة في الوقت المحدد وضمن الميزانية.",
    "why.cta": "ابدأ مشروعك",

    // Commitments
    "commit.label": "التزاماتنا",
    "commit.title1": "مبنيّون",
    "commit.title2": "بهدف",
    "commit.c1.title": "الصحة والسلامة والبيئة",
    "commit.c1.desc": "ثقافة الصفر في الحوادث مع أنظمة إدارة HSE صارمة وعمليات تدقيق منتظمة وتدريب مستمر لجميع العاملين في الموقع.",
    "commit.c2.title": "الاستدامة",
    "commit.c2.desc": "تقليل الأثر البيئي من خلال المصادر المسؤولة للمواد وتقليل النفايات وأساليب البناء الموفرة للطاقة.",
    "commit.c3.title": "المجتمع",
    "commit.c3.desc": "إعطاء الأولوية للتوظيف المحلي وتنمية المهارات والمشاركة المجتمعية في كل منطقة نعمل فيها.",
    "commit.c4.title": "ضمان الجودة",
    "commit.c4.desc": "أنظمة إدارة الجودة المعتمدة بشهادة ISO تضمن أن كل مخرجاتنا تلبي أو تتجاوز مواصفات العملاء والجهات التنظيمية.",
    "commit.banner.title": "هل أنت مستعد لبناء شيء عظيم؟",
    "commit.banner.sub": "تعاون مع إنجازكو في مشروع البنية التحتية أو الإنشاء القادم.",
    "commit.banner.cta": "طلب عرض سعر",

    // Certifications
    "cert.iso9001.title": "إدارة الجودة",
    "cert.iso9001.desc": "تضمن جودة متسقة في تسليم المشاريع والعمليات ورضا العملاء في جميع العمليات.",
    "cert.iso14001.title": "الإدارة البيئية",
    "cert.iso14001.desc": "تُجسّد الالتزام بتقليل الأثر البيئي وممارسات البناء المستدامة.",
    "cert.iso45001.title": "الصحة والسلامة المهنية",
    "cert.iso45001.desc": "توفير بيئة عمل آمنة وصحية من خلال منع الإصابات والأمراض المهنية في جميع المواقع.",
    "cert.iso27001.title": "أمن المعلومات",
    "cert.iso27001.desc": "حماية بيانات الشركة والعملاء من خلال أنظمة إدارة أمن المعلومات الصارمة.",
    "cert.ccc.title": "الامتثال للأمن السيبراني",
    "cert.ccc.desc": "معتمدون بموجب إطار شهادة الامتثال للأمن السيبراني (CCC) الصادرة عن الهيئة الوطنية للأمن السيبراني.",

    // Contact
    "contact.label": "تواصل معنا",
    "contact.title1": "لنبني",
    "contact.title2": "معاً",
    "contact.sub": "هل أنت مستعد لمناقشة مشروعك القادم؟ فريقنا هنا للمساعدة.",
    "contact.form.name": "الاسم الكامل",
    "contact.form.email": "البريد الإلكتروني",
    "contact.form.phone": "رقم الهاتف",
    "contact.form.company": "الشركة / المؤسسة",
    "contact.form.service": "الخدمة المطلوبة",
    "contact.form.message": "تفاصيل المشروع",
    "contact.form.submit": "إرسال الرسالة",
    "contact.form.placeholder.name": "اسمك الكامل",
    "contact.form.placeholder.email": "بريدك@الإلكتروني.com",
    "contact.form.placeholder.phone": "+966 5X XXX XXXX",
    "contact.form.placeholder.company": "اسم شركتك",
    "contact.form.placeholder.message": "أخبرنا عن مشروعك...",
    "contact.info.address": "الرياض، المملكة العربية السعودية",
    "contact.info.phoneVal": "+966 11 4655557",

    // Footer
    "footer.tagline": "نبني البنية التحتية للمملكة العربية السعودية منذ عام 1978.",
    "footer.services": "الخدمات",
    "footer.company": "الشركة",
    "footer.about": "من نحن",
    "footer.projects": "المشاريع",
    "footer.careers": "الوظائف",
    "footer.news": "الأخبار",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.cr": "السجل التجاري",
    "footer.quicklinks": "روابط سريعة",
    "footer.copy": "© 2026 شركة الإنجاز للتجارة والمقاولات. جميع الحقوق محفوظة.",
    "footer.location": "الرياض، المملكة العربية السعودية",
    "contact.intro": "هل أنت مستعد لمناقشة مشروعك القادم؟ فريقنا من المهندسين ومديري المشاريع هنا لمساعدتك في التخطيط والتصميم والتنفيذ.",
    "contact.info.hq": "المقر الرئيسي",
    "contact.info.phone": "الهاتف",
    "contact.info.email": "البريد الإلكتروني",
    "contact.info.jobs": "الوظائف والتوظيف",
    "contact.info.hours": "ساعات العمل",
    "contact.info.hoursVal": "الأحد – الخميس: 7:00 ص – 3:00 م",
    "contact.cr.label": "السجل التجاري",
    "contact.cr.value": "مسجلة في المملكة العربية السعودية",
    "contact.form.namePh": "اسمك الكامل",
    "contact.form.emailPh": "بريدك@الإلكتروني.com",
    "contact.form.companyPh": "اسم شركتك",
    "contact.form.servicePh": "اختر خدمة...",
    "contact.form.messagePh": "أخبرنا عن متطلبات مشروعك...",
    "contact.success.title": "تم الإرسال!",
    "contact.success.sub": "شكراً لتواصلك معنا. سيتواصل فريقنا معك خلال 1–2 يوم عمل.",

    // Awards Section
    "awards.eyebrow": "التميز والتقدير",
    "awards.title": "الجوائز والشهادات",
    "awards.subtitle": "يتجلى التزام الإنجاز بالجودة والسلامة والابتكار من خلال الشهادات المعتمدة دولياً والجوائز الإقليمية وإنجازات السلامة البارزة.",
    "awards.cert.heading": "شهادات ISO الدولية",
    "awards.cert.quality": "إدارة الجودة",
    "awards.cert.quality.desc": "معتمدة لتقديم خدمات البناء عالية الجودة وفق المعايير الدولية.",
    "awards.cert.env": "الإدارة البيئية",
    "awards.cert.env.desc": "ملتزمون بتقليل الأثر البيئي في جميع مواقع المشاريع والعمليات.",
    "awards.cert.ohs": "الصحة والسلامة المهنية",
    "awards.cert.ohs.desc": "ضمان أعلى معايير سلامة العمال والصحة المهنية في كل مشروع.",
    "awards.cert.edu": "إدارة المنظمات التعليمية",
    "awards.cert.edu.desc": "نظام إدارة معتمد لبرامج التدريب والتطوير المهني.",
    "awards.mile.heading": "إنجازات السلامة والتميز",
    "awards.mile1.value": "+2M",
    "awards.mile1.label": "ساعة عمل آمنة",
    "awards.mile1.sub": "نيوم – مشروع ذا لاين، صفر إصابات",
    "awards.mile2.value": "+47",
    "awards.mile2.label": "عاماً من التميز",
    "awards.mile2.sub": "تأسست عام 1978 — في خدمة البنية التحتية السعودية",
    "awards.mile3.value": "+250",
    "awards.mile3.label": "مشروع منجز",
    "awards.mile3.sub": "طرق وجسور وأنفاق وأنابيب ومبانٍ",
    "awards.reg.heading": "الجوائز والترشيحات الإقليمية",
    "awards.reg1.year": "2025",
    "awards.reg1.title": "جوائز المشاريع الشرق الأوسط — التميز في البنية التحتية",
    "awards.reg1.body": "تقدير على التنفيذ المتميز لمشاريع البنية التحتية الكبرى في المملكة، بما فيها خط أنابيب IWTP الجبيل–بريدة.",
    "awards.reg1.org": "Project Awards ME",
    "awards.reg2.year": "2025",
    "awards.reg2.title": "مبادرة الصحة والسلامة للعام",
    "awards.reg2.body": "ترشيح لثقافة السلامة الرقمية التي تمكّن أكثر من 2000 عامل في أحد أكثر مشاريع البنية التحتية تعقيداً في المملكة.",
    "awards.reg2.org": "جوائز Construction Week السعودية",
    "awards.reg3.year": "2024",
    "awards.reg3.title": "جائزة نيوم للإنجاز في السلامة",
    "awards.reg3.body": "مُمنحة من نيوم لتحقيق 2 مليون ساعة عمل آمنة بدون إصابات خلال أعمال التأسيس في مشروع ذا لاين.",
    "awards.reg3.org": "نيوم",
    "awards.reg4.year": "2024",
    "awards.reg4.title": "الراعي الماسي — الطرق السعودية",
    "awards.reg4.body": "تكريم كراعٍ ماسي في معرض Highways Saudi Arabia 2024، تعكساً لريادة الإنجاز في إنشاء الطرق والجسور.",
    "awards.reg4.org": "Highways KSA",
    "awards.gallery.heading": "معرض صور حفل التكريم",
  },
};

/* ---------------------------------------------------------------------------
   Provider
   --------------------------------------------------------------------------- */
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  const setLang = (l: Lang) => {
    setLangState(l);
    document.documentElement.lang = l;
    document.documentElement.dir = l === "ar" ? "rtl" : "ltr";
    localStorage.setItem("enjazco-lang", l);
  };

  useEffect(() => {
    const saved = localStorage.getItem("enjazco-lang") as Lang | null;
    if (saved === "ar" || saved === "en") setLang(saved);
  }, []);

  const t = (key: string): string =>
    translations[lang][key] ?? translations["en"][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL: lang === "ar" }}>
      {children}
    </LanguageContext.Provider>
  );
}
